#!/usr/bin/env python 

import sys, os
sys.path.append("/var/openpanel/api/python/package")
from OpenPanel import coreclient
c = coreclient.CoreSession()

auth_user ="openpanel-admin"
auth_pw   = os.environ["AUTHD_PASSWORD"]

try:
	c.login(user=auth_user, password=auth_pw)
except:
	print "auth_ok:-1"
else:
	print "auth_ok:1"
	print "uid:33"
	print "gid:33"
	print "dir:/var/www"
	print "slow_tilde_expansion:1"

print "end"
